### ISSUE TITLE
make ipymd pip-installable

### ISSUE THREAD

**Issue by gregcaporaso** [rossant/ipymd#52]
Are there any plans to make ipymd pip-installable? I've been doing some experiments with this, and would like to use it for [An Introduction to Applied Bioinformatics](http://www.readIAB.org), but for convenience would either need ipymd to be pip-installable, or to package it in my project. I could help out with getting it pip-installable if that would be useful.

**Comment by rossant** [comment]
Absolutely! I won't have time to do it myself before a couple of weeks, but feel free to propose a PR with a `setup.py`. Then I can upload the package.

**Comment by gregcaporaso** [comment]
Great, thanks @rossant! @johnchase and @jairideout, who also work on IAB (An Introduction to Applied Bioinformatics) are going to try this right now (we're taking part in the Mozilla Science Lab Global Sprint today).

**Comment by rossant** [comment]
PR merged and release done: thanks!!
I know the README is messed up on PyPi -- to be fixed later... Maybe we can add a ReST format to automatically convert Markdown to ReST :)

**Comment by jairideout** [comment]
Awesome, thanks for merging and cutting a release @rossant!

**Comment by johnchase** [comment]
:+1:

**Comment by gregcaporaso** [comment]
This is great news, thanks everyone!
