### ISSUE TITLE
Pandoc support

### ISSUE THREAD

**Issue by rossant** [rossant/ipymd#61]
(assuming pandoc is installed on the user's computer)

Wrapping [pandoc](http://pandoc.org/) would bring support for many languages *for free*, using Markdown as an intermediate language (`ipymd_cells <=> Markdown <=> pandoc languages`), notably:

* ReST
* HTML
* LaTeX
* slides
* ...

**Comment by JanSchulz** [comment]
pypandoc is going to include pandoc binaries in it's wheels (see https://github.com/bebraw/pypandoc/pull/73). 

I also use pypandoc in knitpy.

**Comment by bollwyvl** [comment]
Wow, that's really great news. There has been some talk of refactored
alternate nbconvert around pandoc in the upstream by @minrk.

**Comment by rossant** [comment]
@bollwyvl @minrk I am currently working on a pure Python pandoc-like library with builtin support for ipynb, that will effectively supersede ipymd. I hope to have something to show within a couple of weeks...

**Comment by JanSchulz** [comment]
@rossant You want to build a replacement for pandoc?

**Comment by rossant** [comment]
Nope, not a replacement, more like a (pure Python) companion with full support for Jupyter Notebooks.
