### ISSUE TITLE
nbconvert

### ISSUE THREAD

**Issue by rossant** [rossant/ipymd#66]
I'm wondering whether part or all of ipymd's functionality could/should be integrated in nbconvert, since there is some overlap currently.

The main features would be:

* reverse conversion from ipynb notebooks to various formats (markdown, ODT, etc.). Round-trip conversions should leave files mostly unchanged
* configurable input/output prompts, logic for creating ipynb cells out of standard Markdown documents, etc.

Then, ipymd could leverage nbconvert and implement:

* support for various formats/file extensions (e.g. `.md`) in the Notebook
* on-the-fly conversion when loading/saving a notebook in the Notebook interface, allowing to edit `.md` files directly in the Notebook with no explicit conversion

cc @carreau @minrk

**Comment by Carreau** [comment]
> reverse conversion from ipynb notebooks to various formats (markdown, ODT, etc.). Round-trip conversions should leave files mostly unchanged

Yes definitively it is on our new grant. 



> support for various formats/file extensions (e.g. .md) in the Notebook
> on-the-fly conversion when loading/saving a notebook in the Notebook interface, allowing to edit .md files directly in the Notebook with no explicit conversion

This is not, but I don't have any objections of having that in the long term. Maybe not baked in at the beginning, but having the technical conversions pipeline in nbconvert woudl be good.

**Comment by rossant** [comment]
> Yes definitively it is on our new grant.

good to know

> Maybe not baked in at the beginning, but having the technical conversions pipeline in nbconvert woudl be good.

yep, that's what I had in mind too.

When I have time I'll look into nbconvert's code and see how these features could possibly be integrated

**Comment by minrk** [comment]
Yup, I think the concept of `importers` has made sense as a way in for nbconvert for a while, as the other side of `exporters`. Your experience with ipymd would be useful for that. Like @Carreau, I think supporting multiple formats as the native storage (a la ipymd) is probably not something we should push into core at this point. I think keeping things like ipymd custom contents managers as standalone projects is a good thing, and helps apply pressure for a good plugin interface. If every extension people use is actually part of the core package, there's no pressure for the extension facilities to be any good.

**Comment by rossant** [comment]
@minrk agreed.

On a related note, have you ever considered integrating nbconvert with pandoc? Having .ipynb reader/writer in pandoc would be awesome. I'm not sure how it would work exactly, though; writing new reader/writer in Haskell? [custom filters in Python](http://pandoc.org/scripting.html#but-i-dont-want-to-learn-haskell)?, etc.

It looks like pandoc has a native AST representation of a document, which consists of a linear sequence of blocks. This AST can be represented in JSON. In this respect it is similar to ipymd which represents a notebook as a list of JSON cells (very similar to nbformat).

Then you'd have a single tool to convert notebooks to markdown, odt, docx, latex, etc. and conversely.

**Comment by Carreau** [comment]
@parleur have done that. Maybe not in a nice way, but he had some pretty nice pandoc intermediate AST transform. (A reminder that he might want to open source some of the things he made) 

We though try to avoid pandoc as it is often complex to install.

**Comment by minrk** [comment]
> On a related note, have you ever considered integrating nbconvert with pandoc? 

You bet. I actually think nbconvert would be significantly improved if it were built as extensions to pandoc instead of its own system of pandoc-like things. I'm not sure people would put up with the haskell dependency for *all* conversions, though.

**Comment by rossant** [comment]
Python lacks a pandoc equivalent with native ipynb support... That's actually more or less what ipymd has become (although much more limited than pandoc, obviously).

**Comment by minrk** [comment]
Yup. And I would much rather push pandoc itself than build a clone in Python, but unfortunately I do not think that is feasible.

**Comment by rossant** [comment]
closing in favor of https://github.com/podoc/podoc/issues/18
