### ISSUE TITLE
ipymd broken in IPython 4.0

### ISSUE THREAD

**Issue by rossant** [rossant/ipymd#67]
`jupyter notebook --NotebookApp.contents_manager_class=ipymd.IPymdContentsManager`

error message:

````
[C 14:00:12.838 NotebookApp] Bad config encountered during initialization:
[C 14:00:12.838 NotebookApp] The 'contents_manager_class' trait of a NotebookApp 
instance must be a subclass of 'notebook.services.contents.manager.ContentsManager', 
but a value of class 'traitlets.traitlets.MetaHasTraits' 
(i.e. <class 'ipymd.core.contents_manager.IPymdContentsManager'>) 
was specified.
````

declaration of the class as follows:

```python
class IPymdContentsManager(FileContentsManager, Configurable):
```

@carreau @minrk any ideas?

**Comment by Carreau** [comment]
Do a conditional import of `FileContentsManager, Configurable`

```
try:
   from traitlets.config import Configurable
Except ImportError:
   from IPython.traitlets.config....
```

Same with `from notebook... import FileContensManager`. 

The class have the same name but have moved into another package. 
The importer probably don't like the shims, I had the same issue with jupyterdrive:

https://github.com/jupyter/jupyter-drive/blob/master/jupyterdrive/clientsidenbmanager.py#L8-L11

**Comment by rossant** [comment]
thanks @Carreau !
