### ISSUE TITLE
unicode in python output

### ISSUE THREAD

**Issue by RafalSkolasinski** [rossant/ipymd#72]
Hi, I noticed that `ipymd` cannot save `md` file when python output contains unicode.

Following code

```
import sympy
from sympy.interactive import printing
printing.init_printing(use_latex='mathjax')
x,y,z = sympy.symbols('x y z')
expr = x**2 + x*y
expr
```

throws errors like
`
Error while saving file: ideas/graphs.md 'ascii' codec can't encode character u'\u22c5' in position 189: ordinal not in range(128)
`

**Comment by rossant** [comment]
Python 2 or 3?

**Comment by RafalSkolasinski** [comment]
``jupyter notebook`` started in python 2 and also kernel on python 2

**Comment by rossant** [comment]
So the fix seems to be to use Python 3. thanks :)
