### ISSUE TITLE
timeline for a next release?

### ISSUE THREAD

**Issue by gregcaporaso** [rossant/ipymd#75]
@rossant, do you have an ETA for another release of ipymd on pypi? We're relying on some functionality in master in a couple of projects now, so we're having to pip install from master a lot. We could help with a release again if needed.

**Comment by rossant** [comment]
Would love some help with this! I can give you admin/commit rights if you want.

I'm currently working on a [more general conversion library](https://github.com/podoc/podoc/) that would include all of ipymd's functionality and much more.

**Comment by gregcaporaso** [comment]
Ok, thanks @rossant. It'd probably make sense for us to not have commit access, but rather run pull requests through you. What do you think? We'd also rather not have your pypi credentials, so maybe when we have something ready we can just ask you to do the final upload? I would likely then mirror the pypi release on my conda channel.

**Comment by gregcaporaso** [comment]
And looking forward to podoc!

**Comment by rossant** [comment]
Sure no problem!

**Comment by rossant** [comment]
@gregcaporaso I uploaded a new version (`0.1.2`) on PyPI. Is it working for you? If so, feel free to close this issue.

**Comment by gregcaporaso** [comment]
It's working for me, thanks @rossant!
