### ISSUE TITLE
Jupyter Notebook >=4.3.2 adds "editable" and "deletable" metadata to every cell

### ISSUE THREAD

**Issue by ariddell** [rossant/ipymd#80]
This is potentially an issue but certainly an FYI.

If you have a markdown notebook with 100 cells, you're going to get 100 instances of

```
---
deletable: true
editable: true
...
```

added to your markdown notebook when you save the file.

**Comment by rossant** [comment]
Thanks! should be fixed now (only cell metadata that differs from this default will be saved).
