### ISSUE TITLE
Hook to compare the actual last modified time of ipynb and md files.

### ISSUE THREAD

**Issue by stanleyng8** [rossant/ipymd#91]
I am using ipymd to programmatically convert to and from ipynb and md files. I only store the md files in my git repo which is then pulled by the various computers that I use. Currently, I scan the modified time of the files. So the newer file (say it is test.md) gets converted and overwrites the older version, test.ipynb. Obviously this is not foolproof and even unchanged files will change simply because the conversion swings back and forth as the files will never have the same last modified time.

Is there some sort of hook that I can use to compare both the ipynb and md files. Is there some sort of timestamp in both the files? I opened up the ipynb file in a text editor and I don't see a timestamp in there. Should I explicitly add a timestamp field into one of my cells and run that every time I update the notebook? Then before running the ipymd, first scan for that timestamp field within both the ipymd and md files. Use the result to decide whether a conversion is needed and the direction of the conversion. Any suggestions for improvements to this approach or recommendations for another approach would be most welcomed.

**Comment by rossant** [comment]
Do you mean that you have every notebook in two separate formats, md and ipynb, and that you may modify either of them at any given time? The least risky option is just to have a single format that you use, typically md, and that you can edit directly in a Jupyter notebook. Maintaining two editable copies of a given document is quite tricky.

**Comment by stanleyng8** [comment]
I have two formats for every notebook. I work only on the ipynb format but I put the md under git version control. I work on multiple machines running different OSes and the md version is portable whereas I have experienced some issues with ipynb that has cost me quite a few work days. With an internal (probably self-generated at this stage as I don't see anything builtin) timestamp, I can then write a script to compare the two formats and update whatever is necessary across my entire repo.
